<div>
    <form action="" method="post" class="gtrwebsite-dialog">
        <table>
            <tr>
                <th>{$lng_label_contact_name}:</th>
                <td>
                    {$gtrwebsite_contact_name_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_stored}:</th>
                <td>
                    {$gtrwebsite_contact_stored_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_surname}:</th>
                <td>
                    {$gtrwebsite_contact_surname_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_address}</th>
                <td>
                    {$gtrwebsite_contact_address_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_city}:</th>
                <td>
                    {$gtrwebsite_contact_city_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_provincia}:</th>
                <td>
                    {$gtrwebsite_contact_provincia_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_postCode}:</th>
                <td>
                    {$gtrwebsite_contact_postCode_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_tel}:</th>
                <td>
                    {$gtrwebsite_contact_tel_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_email}:</th>
                <td>
                  {$gtrwebsite_contact_email_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_info}:</th>
                <td>
                    {$gtrwebsite_contact_info_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_action}:</th>
                <td>
                    {$gtrwebsite_contact_action_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_keepUpdated}:</th>
                <td>
                    {$gtrwebsite_contact_keepUpdated_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_barrier}:</th>
                <td>
                    {$gtrwebsite_contact_barrier_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_bathroom}:</th>
                <td>
                    {$gtrwebsite_contact_bathroom_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_kitchen}:</th>
                <td>
                    {$gtrwebsite_contact_kitchen_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_comfort}:</th>
                <td>
                    {$gtrwebsite_contact_comfort_input}
                </td>
            </tr>
            <tr>
                <th>{$lng_label_contact_sense}:</th>
                <td>
                    {$gtrwebsite_contact_sense_input}
                </td>
            </tr>            
        </table>
    </form>
</div>

{literal}
    {/literal}{$jsdocready}{literal}
{/literal}
