<table class="statistic-table">
    <tr>
        <th>{$lng_label_statistic_total_photo}:</th>
        <td>{$totalPhoto}</td>
    </tr>
    <!--
    <tr>
        <th>{$lng_label_statistic_total_photousedspace}:</th>
        <td>{$totalPhotoUsedSpace}</td>
    </tr>
    -->
    <tr>
        <th>{$lng_label_statistic_user_quota}:</th>
        <td>{$userQuota}</td>
    </tr>
    <tr>
        <th>{$lng_label_statistic_total_size}:</th>
        <td>{$totalFileSize}</td>
    </tr>
    <tr>
        <th>{$lng_label_statistic_remaining_quota}:</th>
        <td>{$remainingQuota}</td>
    </tr>
    <tr>
        <th>{$lng_label_statistic_remaining_month_quota}:</th>
        <td>{$remainingMonthQuota}</td>
    </tr>
</table>