INSERT INTO `shinticket_ticket` (`idTicket`, `userId`, `applicationId`, `title`, `body`, `priority`, `status`, `created`, `lastupdate`, `attachPath`, `realAttachFileName`) VALUES 
(1, 1, 1, 'Would you mark which is correct?', 'The SR Leader class was a class of experimental 0-6-6-0 articulated steam locomotive, produced to the design of the innovative engineer Oliver Bulleid. The Leader was an attempt to extend the life of steam traction on Britain\'s railways by eliminating many of the operational drawbacks associated with existing steam locomotives. It was intended as a replacement for the ageing fleet of M7 class tank engines still in operation on the Southern Railway  (SR). Design work began in 1946, and development continued after the nationalisation of the railways in 1948, under the auspices of British Railways (BR).', 'n', 'c', '2010-09-22 14:32:23', '2010-09-22 14:32:23', NULL, NULL),
(2, 1, 5, 'Could you answer my question?', 'This plugin (it can be downloaded from http://www.7-zip.org) supports only the following archive types: 7z, arj, bzip2, cab, cpio, gzip, rar, rpm, tar and zip. Unlike MultiArc, 7-zip contains all the necessary code for supporting these archive types and does not require any additional archivers.', 'n', 's', '2010-09-21 14:32:29', '2010-09-21 14:32:29', NULL, NULL),
(3, 1, 3, 'Could you give an answer to my question?', 'Advantages: the MultiArc plugin supports dozens of archive types and other files with a structure defined by some rules. It is also extensible, meaning that support for almost any archiver can be added if necessary.', 'l', 'a', '2010-07-22 11:12:13', '2010-07-22 11:12:13', NULL, NULL),
(4, 1, 4, 'Where is my archive !!!!?????', 'Viewing archive contents is done by the plugin itself, through the respective plugin extension module (<ArchiveType>.fmt) or by calling (automatically and invisibly for the user) external utility programs.', 'a', 'a', '2010-05-23 15:34:21', '2010-05-23 15:34:21', NULL, NULL),
(5, 1, 5, 'How i can make modify archives?', 'To create or modify archives, external archiver programs are used. In order to make it possible to use those programs, MultiArc must be able to locate them. This usually means that all archivers are stored in a single directory that is listed in the environment variable %PATH% (if you do not understand this, consult your system administrator or another computer specialist)', 'h', 'a', '2010-01-12 17:23:32', '2010-01-12 17:23:32', NULL, NULL),
(6, 1, 1, 'Please help with SMARTY!', 'This directory contains the documentation for Smarty. All files are in docbook format with an .xml extention. Different subdirs contain different available languages.', 'h', 'd', '2010-09-20 14:32:25', '2010-05-20 14:32:25', NULL, NULL),
(7, 1, 2, 'Тест сообщения на русском?', 'Здравствуйте. Это луркоморье — русский луркмоар. Вы можете редактировать любую статью, так же, как и в википедии. Но, в отличие от википедии, мы не ставим своей целью написать обо всем на свете сразу и не руководствуемся мифическими критериями «значимости» и «энциклопедичности». Само получается.', 'a', 'd', '2010-09-02 11:56:13', '2010-08-02 11:56:13', NULL, NULL),
(8, 1, 3, 'Sed omnia praeclara tam difficilia, quam rara sunt?', 'Questa pagina contiene una lista di voci che i wikipediani  ritengono particolarmente complete, corrette ed accurate nonché piacevoli da leggere. Per segnalare una voce da aggiungere alla lista o da eliminare da questa pagina indicalo in voci segnalate, dove sarà giudicata per stile, prosa, esaustività e neutralità. Una piccola stella dorata Crystal Clear action bookmark.png nella parte in alto a destra della voce indica che quella voce è attualmente in vetrina. Un\'altra piccola stella dorata nell\'elenco degli interwiki indica che quella voce è in vetrina in un\'altra lingua. Per l\'elenco completo, è possibile consultare la categoria voci di qualità in altre lingue.', 'l', 'c', '2010-09-22 21:41:21', '2010-01-22 21:41:21', NULL, NULL),
(9, 1, 4, ' Tutte le cose eccellenti sono tanto difficili, quanto rare?', 'Pisanello era noto soprattutto per splendidi affreschi  di grandi dimensioni, sospesi tra realismo e mondo fantastico, popolati da innumerevoli figure, con colori brillanti e tratti precisi; essi furono in larghissima parte distrutti, a causa di incidenti, dell\'incuria o di distruzioni volontarie, per via del mutare del gusto, soprattutto nei secoli del Rinascimento e del Barocco. Nell\'arco della sua carriera artistica si dedicò con successo anche all\'attività di medaglista, raggiungendo vertici che, secondo alcuni, sono in questo campo insuperati.', 'l', 's', '2010-09-22 18:34:53', '2010-09-22 18:34:53', NULL, NULL);